# adapted from https://github.com/aspnetboilerplate/.github/blob/main/policies/cla.yml#L18
name: Contributor License Agreement Policy
description: .NET Foundation CLA policy file

resource: repository

configuration: 
  cla:
    # Point this to YOUR repo's CLA file
    content: https://raw.githubusercontent.com/DeveloperTryingToCodeLikeOtherOfThem/pxt-hardware-programming-docs/master/CLA.md
    minimalChangeRequired: 
       files: 1
       codeLines: 1
    # This list is great—it keeps your helpful bots working
    bypassUsers:
       - dependabot[bot]
       - renovate[bot]
       - github-actions[bot]
